// Generated by https://quicktype.io

export interface Pedido {
    status: string;
    sale:   PedidoId;
}

export interface PedidoId {
    _id:             string;
    date:            string;
    solicitante:     string;
    producto_nombre: string;
    cantidad:        string;
    telefono:        string;
    direccion:       string;
    datos:           string;
    estado:          string;
    total:           string;
    image:           string;
    __v:             number;
}
