// Generated by https://quicktype.io

export interface ProfileRespnse {
    status:  string;
    profile: Profile;
}

export interface Profile {
    _id:       string;
    date:      string;
    nombre:    string;
    apellido:  string;
    email:     string;
    telefono:  string;
    direccion: string;
    image:     string;
    __v:       number;
}
