// Generated by https://quicktype.io

export interface UserResponse {
    status:   string;
    products: Product[];
}

export interface Product {
    _id:        string;
    nombre:     string;
    correo:     string;
    contraseña: string;
    usuario:    Usuario;
    __v:        number;
}

export enum Usuario {
    Administrador = "Administrador",
    Cliente = "Cliente",
    Iiiiiiiiiiii = "iiiiiiiiiiii",
}
