// Generated by https://quicktype.io

export interface SaveSales {
    status:  string;
    product: Product;
}

export interface Product {
    _id:             string;
    date:            string;
    solicitante:     string;
    producto_nombre: string;
    cantidad:        string;
    telefono:        string;
    datos:           string;
    estado:          string;
    total:           string;
    image:           null;
    __v:             number;
}


// Generated by https://quicktype.io

export interface PerfilResponse {
    status:   string;
    perfiles: Perfiles[];
}

export interface Perfiles {
    _id:       string;
    date:      string;
    nombre:    string;
    apellido:  string;
    email:     string;
    telefono:  string;
    direccion: string;
    estatus?:  string;
    image:     null | string;
    __v:       number;
}
